### ISSUE TITLE
Docker Version Error 500

### ISSUE THREAD

**Issue by jpcapone** [adrian-dobre/BlinkWebService#13]
After deploying the container and attempting to log in I get: Request failed with status code 500 at the top of the page.  Here are some of the container logs.  
`2023-01-31 02:50:54.389 DEBUG 1 --- [-nio-80-exec-10] o.a.c.c.C.[Tomcat].[localhost]           : Processing ErrorPage[errorCode=0, location=/error]
2023-01-31 02:50:54.389 DEBUG 1 --- [-nio-80-exec-10] o.s.web.servlet.DispatcherServlet        : "ERROR" dispatch for POST "/error", parameters={}
2023-01-31 02:50:54.389 DEBUG 1 --- [-nio-80-exec-10] pertySourcedRequestMappingHandlerMapping : looking up handler for path: /error
2023-01-31 02:50:54.389 DEBUG 1 --- [-nio-80-exec-10] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController#error(HttpServletRequest)
2023-01-31 02:50:54.390 DEBUG 1 --- [-nio-80-exec-10] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Using 'application/json', given [application/json, text/plain, */*] and supported [application/json, application/*+json, application/json, application/*+json, application/xml;charset=UTF-8, text/xml;charset=UTF-8, application/*+xml;charset=UTF-8, application/xml;charset=UTF-8, text/xml;charset=UTF-8, application/*+xml;charset=UTF-8]
2023-01-31 02:50:54.390 DEBUG 1 --- [-nio-80-exec-10] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Writing [{timestamp=Tue Jan 31 02:50:54 GMT 2023, status=500, error=Internal Server Error, message=External A (truncated)...]
2023-01-31 02:50:54.390 DEBUG 1 --- [-nio-80-exec-10] o.a.c.http11.filters.GzipOutputFilter    : Flushing the compression stream!
2023-01-31 02:50:54.390 DEBUG 1 --- [-nio-80-exec-10] o.a.c.http11.filters.GzipOutputFilter    : Flushing the compression stream!
2023-01-31 02:50:54.390 DEBUG 1 --- [-nio-80-exec-10] o.a.c.http11.filters.GzipOutputFilter    : Flushing the compression stream!
2023-01-31 02:50:54.390 DEBUG 1 --- [-nio-80-exec-10] o.a.c.http11.filters.GzipOutputFilter    : Flushing the compression stream!
2023-01-31 02:50:54.390 DEBUG 1 --- [-nio-80-exec-10] o.s.web.servlet.DispatcherServlet        : Exiting from "ERROR" dispatch, status 500
2023-01-31 02:50:54.390 DEBUG 1 --- [-nio-80-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    :  Disabling the response for further output
2023-01-31 02:50:54.391 DEBUG 1 --- [-nio-80-exec-10] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@630a5728:org.apache.tomcat.util.net.NioChannel@f7e876:java.nio.channels.SocketChannel[connected local=/172.17.0.3:80 remote=/10.229.181.191:60308]], Status in: [OPEN_READ], State out: [CLOSED]
2023-01-31 02:50:54.391 DEBUG 1 --- [-nio-80-exec-10] o.apache.tomcat.util.threads.LimitLatch  : Counting down[http-nio-80-exec-10] latch=2
2023-01-31 02:50:54.391 DEBUG 1 --- [-nio-80-exec-10] org.apache.tomcat.util.net.NioEndpoint   : Calling [org.apache.tomcat.util.net.NioEndpoint@5345f31c].closeSocket([org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@630a5728:org.apache.tomcat.util.net.NioChannel@f7e876:java.nio.channels.SocketChannel[connected local=/172.17.0.3:80 remote=/10.229.181.191:60308]])
2023-01-31 02:51:37.363 DEBUG 1 --- [p-nio-80-exec-3] o.apache.tomcat.util.threads.LimitLatch  : Counting down[http-nio-80-exec-3] latch=1
2023-01-31 02:51:37.363 DEBUG 1 --- [p-nio-80-exec-3] org.apache.tomcat.util.net.NioEndpoint   : Calling [org.apache.tomcat.util.net.NioEndpoint@5345f31c].closeSocket([org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@3b0d9916:org.apache.tomcat.util.net.NioChannel@647406fb:java.nio.channels.SocketChannel[connected local=/172.17.0.3:80 remote=/10.229.181.191:60307]])
2023-01-31 02:51:44.625 DEBUG 1 --- [alina-utility-1] org.apache.catalina.session.ManagerBase  : Start expire sessions StandardManager at 1675133504624 sessioncount 0
2023-01-31 02:51:44.625 DEBUG 1 --- [alina-utility-1] org.apache.catalina.session.ManagerBase  : End expire sessions StandardManager processingTime 1 expired sessions: 0
2023-01-31 02:52:44.625 DEBUG 1 --- [alina-utility-1] org.apache.catalina.session.ManagerBase  : Start expire sessions StandardManager at 1675133564625 sessioncount 0
2023-01-31 02:52:44.626 DEBUG 1 --- [alina-utility-1] org.apache.catalina.session.ManagerBase  : End expire sessions StandardManager processingTime 0 expired sessions: 0
2023-01-31 02:53:44.626 DEBUG 1 --- [alina-utility-2] org.apache.catalina.session.ManagerBase  : Start expire sessions StandardManager at 1675133624626 sessioncount 0
2023-01-31 02:53:44.626 DEBUG 1 --- [alina-utility-2] org.apache.catalina.session.ManagerBase  : End expire sessions StandardManager processingTime 0 expired sessions: 0
2023-01-31 02:54:44.627 DEBUG 1 --- [alina-utility-2] org.apache.catalina.session.ManagerBase  : Start expire sessions StandardManager at 1675133684627 sessioncount 0
2023-01-31 02:54:44.627 DEBUG 1 --- [alina-utility-2] org.apache.catalina.session.ManagerBase  : End expire sessions StandardManager processingTime 0 expired sessions: 0
`
Please advise.

**Comment by tidusjar** [comment]
I have the same Issue. I'm assuming it's to do with 2FA


```
--> POST https://rest-prod.immedia-semi.com/api/v4/account/login
Body : {"email":"REDACTED","password":"REDACTED","app_version":"6.0.10 (8280) #881c8812","client_name":"Blink iPhone","client_type":"ios","device_identifier":"iPhone12,3","notification_key":"REDACTED","os_version":"13.5","unique_id":"REDACTED"}
Headers : (5)
accept-language : en-US
user-agent : Blink/8280 CFNetwork/1126 Darwin/19.5.0
locale : en_US
app-build : IOS_8280
Content-Type : text/plain; charset=UTF-8

2023-02-13 10:58:11.370 DEBUG 1 --- [p-nio-80-exec-7] o.s.web.servlet.DispatcherServlet        : Failed to complete request: java.lang.RuntimeException: External API Error: Unexpected HTTP Status Code -1. Details:
 <-- -1 https://rest-prod.immedia-semi.com/api/v4/account/login
Response :
Length : 0
Body : (empty)
Headers : (0)

2023-02-13 10:58:11.372 ERROR 1 --- [p-nio-80-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: External API Error: Unexpected HTTP Status Code -1. Details:
 <-- -1 https://rest-prod.immedia-semi.com/api/v4/account/login
Response :
Length : 0
Body : (empty)
Headers : (0)
] with root cause

java.lang.RuntimeException: External API Error: Unexpected HTTP Status Code -1. Details:
 <-- -1 https://rest-prod.immedia-semi.com/api/v4/account/login
Response :
Length : 0
Body : (empty)
Headers : (0)

        at ui.web.blink.infrastructure.helpers.BaseService.baseRequest(BaseServiceClient.kt:157) ~[classes!/:na]
        at ui.web.blink.infrastructure.helpers.BaseService.post(BaseServiceClient.kt:196) ~[classes!/:na]
        at ui.web.blink.infrastructure.repositories.impl.blink.AuthRepositoryImpl.login(AuthRepositoryImpl.kt:79) ~[classes!/:na]
        at ui.web.blink.application.controllers.AuthController.login(AuthController.kt:27) ~[classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.29.jar!/:9.0.29]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]

2023-02-13 10:58:11.374 DEBUG 1 --- [p-nio-80-exec-7] o.a.c.c.C.[Tomcat].[localhost]           : Processing ErrorPage[errorCode=0, location=/error]
2023-02-13 10:58:11.375 DEBUG 1 --- [p-nio-80-exec-7] o.s.web.servlet.DispatcherServlet        : "ERROR" dispatch for POST "/error", parameters={}
2023-02-13 10:58:11.375 DEBUG 1 --- [p-nio-80-exec-7] pertySourcedRequestMappingHandlerMapping : looking up handler for path: /error
2023-02-13 10:58:11.376 DEBUG 1 --- [p-nio-80-exec-7] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController#error(HttpServletRequest)
2023-02-13 10:58:11.388 DEBUG 1 --- [p-nio-80-exec-7] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Using 'application/json', given [application/json, text/plain, */*] and supported [application/json, application/*+json, application/json, application/*+json, application/xml;charset=UTF-8, text/xml;charset=UTF-8, application/*+xml;charset=UTF-8, application/xml;charset=UTF-8, text/xml;charset=UTF-8, application/*+xml;charset=UTF-8]
2023-02-13 10:58:11.389 DEBUG 1 --- [p-nio-80-exec-7] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Writing [{timestamp=Mon Feb 13 10:58:11 GMT 2023, status=500, error=Internal Server Error, message=External A (truncated)...]

```

**Comment by pgk83** [comment]
Detailed Breakdown
The Trigger: A user (or process) tries to log in. This hits your Spring Boot application at ui.web.blink.application.controllers.AuthController.login.

The Internal Call: Your AuthController calls AuthRepositoryImpl.login, which in turn calls BaseService.post. This BaseService is acting as an HTTP client, making a POST request to an external service to validate the login.

The Core Problem (The 426 Error): The external service (which is behind CloudFront and an Nginx server) responds with Status: 426 Upgrade Required.

A 426 status code means the server refuses to handle the request using the current protocol (like standard HTTP/1.1) and requires the client (your BaseService) to upgrade to a different protocol, most commonly WebSocket (ws:// or wss://).

The X-Cache: Error from cloudfront header confirms that CloudFront also saw this as an unusual or errored response from the origin server.

The Application Crash: Your BaseService.baseRequest method receives this 426 response, doesn't have logic to handle it, and throws an exception.

The Final Result (The 500 Error): The exception travels all the way up the stack. Spring's error handler catches this unhandled exception and, as shown in the final log lines, generates a status=500, error=Internal Server Error response to the original client that tried to log in.

How to Fix It
You need to investigate the downstream service that your BaseService is calling.

Check the Service: Identify the URL that BaseService.baseRequest is trying to POST to.

Check its Configuration: Find out why that service is suddenly demanding a protocol upgrade (426). Was it recently updated? Is it expecting a WebSocket connection for authentication now?

Update Your Code: Once you know why, you have two options:

If the 426 is correct: You must update your BaseService client (e.g., BaseServiceClient.kt) to use a WebSocket client instead of a standard HTTP client to communicate with that service.

If the 426 is wrong: The downstream service (or its Nginx/CloudFront configuration) is misconfigured and needs to be fixed to accept standard POST requests again.

**Comment by adrian-dobre** [comment]
Hey guys! Unfortunately I don’t have much spare tome to maintain this (as you probably saw from the lack of updates) Blink devs regularly update their APIs and deprecate old ones, so problems like this will happen often, unless somebody keeps the APIs updated.
Since there wasn’t much interest into the project and I don’t have much spare time to investigate and fix this, the project will likely die off. Unless someone else picks it up…
